import { QuizQuestionRaw } from './quiz-types';

export const INITIAL_QUIZ_QUESTIONS: QuizQuestionRaw[] = [
  {
    id: 'q-001',
    question: 'Segundo as Escrituras, quem construiu a arca para salvar sua família e os animais do dilúvio?',
    option_a: 'Abraão',
    option_b: 'Noé',
    option_c: 'Moisés',
    option_d: 'Ló',
    correct_answer: 'B',
    explanation: 'Deus ordenou a Noé que construísse uma grande arca de madeira de gofer por causa de sua fidelidade e integridade diante do dilúvio.',
    biblical_reference: 'Gênesis 6:13-14',
    difficulty: 'facil',
    category: 'Antigo Testamento',
    active: true,
  },
  {
    id: 'q-002',
    question: 'Quem subiu ao Monte Sinai e recebeu de Deus as duas tábuas de pedra com os Dez Mandamentos?',
    option_a: 'Josué',
    option_b: 'Arão',
    option_c: 'Moisés',
    option_d: 'Gideão',
    correct_answer: 'C',
    explanation: 'Moisés subiu ao cume do Monte Sinai, onde o Senhor falou com ele e entregou a Lei gravada em tábuas de pedra.',
    biblical_reference: 'Êxodo 20:1-17; 31:18',
    difficulty: 'facil',
    category: 'Antigo Testamento',
    active: true,
  },
  {
    id: 'q-003',
    question: 'Qual jovem pastor derrotou o gigante Golias utilizando uma funda e uma pedra?',
    option_a: 'Sansão',
    option_b: 'Davi',
    option_c: 'Salomão',
    option_d: 'Jônatas',
    correct_answer: 'B',
    explanation: 'Davi, ainda moço e pastor de ovelhas, foi contra Golias em nome do Senhor dos Exércitos e o venceu com uma atiradeira.',
    biblical_reference: '1 Samuel 17:48-50',
    difficulty: 'facil',
    category: 'Personagens Bíblicos',
    active: true,
  },
  {
    id: 'q-004',
    question: 'Em qual cidade Jesus Cristo nasceu, conforme anunciado pelas profecias?',
    option_a: 'Nazaré',
    option_b: 'Jerusalém',
    option_c: 'Belém da Judeia',
    option_d: 'Cafarnaum',
    correct_answer: 'C',
    explanation: 'Jesus nasceu em Belém da Judeia nos dias do rei Herodes, cumprindo a profecia de Miqueias 5:2.',
    biblical_reference: 'Mateus 2:1; Miqueias 5:2',
    difficulty: 'facil',
    category: 'Novo Testamento',
    active: true,
  },
  {
    id: 'q-005',
    question: 'Quem foi lançado na cova dos leões por se recusar a deixar de orar ao Deus verdadeiro?',
    option_a: 'Daniel',
    option_b: 'Sadraque',
    option_c: 'Mesaque',
    option_d: 'Abede-Nego',
    correct_answer: 'A',
    explanation: 'Daniel manteve seu hábito diário de orar três vezes ao dia em direção a Jerusalém e foi protegido por um anjo do Senhor na cova dos leões.',
    biblical_reference: 'Daniel 6:10, 22',
    difficulty: 'facil',
    category: 'Profetas',
    active: true,
  },
  {
    id: 'q-006',
    question: 'Qual foi o primeiro milagre registrado de Jesus durante seu ministério terreno?',
    option_a: 'A cura do cego de nascença',
    option_b: 'A multiplicação dos pães e peixes',
    option_c: 'Transformar água em vinho nas bodas de Caná',
    option_d: 'A ressurreição de Lázaro',
    correct_answer: 'C',
    explanation: 'Jesus realizou o primeiro de Seus sinais em Caná da Galileia ao transformar água em vinho durante uma festa de casamento.',
    biblical_reference: 'João 2:1-11',
    difficulty: 'facil',
    category: 'Jesus e Evangelhos',
    active: true,
  },
  {
    id: 'q-007',
    question: 'Quantos discípulos mais próximos Jesus escolheu como Seus apóstolos?',
    option_a: '7',
    option_b: '10',
    option_c: '12',
    option_d: '70',
    correct_answer: 'C',
    explanation: 'Jesus subiu ao monte e chamou para Si os doze discípulos para estarem com Ele e para enviá-los a pregar.',
    biblical_reference: 'Marcos 3:13-14',
    difficulty: 'facil',
    category: 'Jesus e Evangelhos',
    active: true,
  },
  {
    id: 'q-008',
    question: 'Qual apóstolo negou Jesus três vezes antes do galo cantar, mas depois foi restaurado com amor?',
    option_a: 'Tiago',
    option_b: 'Pedro',
    option_c: 'João',
    option_d: 'Tomé',
    correct_answer: 'B',
    explanation: 'Simão Pedro negou conhecer Jesus no pátio do sumo sacerdote, chorou amargamente ao se arrepender e foi restaurado à beira do mar da Galileia.',
    biblical_reference: 'Lucas 22:60-62; João 21:15-17',
    difficulty: 'facil',
    category: 'Novo Testamento',
    active: true,
  },
  {
    id: 'q-009',
    question: 'Quem foi engolido por um grande peixe após tentar fugir da ordem de Deus para pregar em Nínive?',
    option_a: 'Jonas',
    option_b: 'Jeremias',
    option_c: 'Oséias',
    option_d: 'Miqueias',
    correct_answer: 'A',
    explanation: 'Jonas tomou um navio para Társis fugindo do Senhor, foi lançado ao mar e permaneceu três dias e três noites no ventre de um grande peixe.',
    biblical_reference: 'Jonas 1:1-3, 17',
    difficulty: 'facil',
    category: 'Profetas',
    active: true,
  },
  {
    id: 'q-010',
    question: 'Qual livro da Bíblia é conhecido como o livro dos cânticos, louvores e orações poéticas?',
    option_a: 'Provérbios',
    option_b: 'Eclesiastes',
    option_c: 'Salmos',
    option_d: 'Cantares',
    correct_answer: 'C',
    explanation: 'O livro de Salmos (Tehillim) é a coletânea sagrada de 150 hinos, orações e louvores poéticos do povo de Deus.',
    biblical_reference: 'Salmos 150:6',
    difficulty: 'facil',
    category: 'Poesia e Sabedoria',
    active: true,
  },
  {
    id: 'q-011',
    question: 'Qual rei de Israel pediu sabedoria a Deus em vez de riquezas ou vida longa?',
    option_a: 'Saul',
    option_b: 'Davi',
    option_c: 'Salomão',
    option_d: 'Ezequias',
    correct_answer: 'C',
    explanation: 'Deus apareceu a Salomão em sonho e lhe disse para pedir o que quisesse. Salomão pediu um coração sábio e prudente para julgar o povo.',
    biblical_reference: '1 Reis 3:5-12',
    difficulty: 'facil',
    category: 'Reis de Israel',
    active: true,
  },
  {
    id: 'q-012',
    question: 'Em qual estrada o apóstolo Paulo teve um encontro transformador com a luz de Cristo ressurreto?',
    option_a: 'Estrada de Jericó',
    option_b: 'Estrada de Damasco',
    option_c: 'Caminho de Emaús',
    option_d: 'Via Ápia de Roma',
    correct_answer: 'B',
    explanation: 'Saulo viajava para Damasco com cartas para prender os crentes quando foi cercado por uma forte luz do céu e ouviu a voz de Jesus.',
    biblical_reference: 'Atos 9:1-6',
    difficulty: 'facil',
    category: 'Igreja Primitiva',
    active: true,
  },
  {
    id: 'q-013',
    question: 'Qual mulher judia se tornou rainha da Pérsia e arriscou a própria vida para salvar seu povo do extermínio?',
    option_a: 'Rute',
    option_b: 'Ester',
    option_c: 'Sara',
    option_d: 'Rebeca',
    correct_answer: 'B',
    explanation: 'A rainha Ester declarou: "Se perecer, pereci" e compareceu perante o rei Assuero sem ser chamada, desmascarando a conspiração de Hamã.',
    biblical_reference: 'Ester 4:16; 7:3-6',
    difficulty: 'medio',
    category: 'Personagens Bíblicos',
    active: true,
  },
  {
    id: 'q-014',
    question: 'Quem subiu em uma árvore figueira brava (sicômoro) para conseguir ver Jesus passar em Jericó?',
    option_a: 'Nicodemos',
    option_b: 'Zaqueu',
    option_c: 'Bartimeu',
    option_d: 'Cornélio',
    correct_answer: 'B',
    explanation: 'Zaqueu, o chefe dos publicanos que era de baixa estatura, correu à frente e subiu num sicômoro para enxergar Jesus.',
    biblical_reference: 'Lucas 19:1-6',
    difficulty: 'facil',
    category: 'Jesus e Evangelhos',
    active: true,
  },
  {
    id: 'q-015',
    question: 'Quantos dias e noites choveu ininterruptamente sobre a terra durante o dilúvio?',
    option_a: '7 dias',
    option_b: '40 dias e 40 noites',
    option_c: '100 dias',
    option_d: '150 dias',
    correct_answer: 'B',
    explanation: 'Gênesis 7:12 relata que caiu chuva sobre a terra durante quarenta dias e quarenta noites sem cessar.',
    biblical_reference: 'Gênesis 7:12',
    difficulty: 'facil',
    category: 'Antigo Testamento',
    active: true,
  },
  {
    id: 'q-016',
    question: 'Qual profeta foi arrebatado ao céu num redemoinho acompanhado por um carro e cavalos de fogo?',
    option_a: 'Eliseu',
    option_b: 'Elias',
    option_c: 'Isaías',
    option_d: 'Enoque',
    correct_answer: 'B',
    explanation: 'Elias e Eliseu conversavam perto do rio Jordão quando um carro de fogo os separou e Elias subiu ao céu num redemoinho.',
    biblical_reference: '2 Reis 2:11',
    difficulty: 'medio',
    category: 'Profetas',
    active: true,
  },
  {
    id: 'q-017',
    question: 'Qual é o versículo bíblico considerado o resumo do Evangelho da graça ("Porque Deus amou o mundo de tal maneira...")?',
    option_a: 'Romanos 8:28',
    option_b: 'João 3:16',
    option_c: 'Efésios 2:8',
    option_d: 'Filipenses 4:13',
    correct_answer: 'B',
    explanation: 'João 3:16 afirma: "Porque Deus amou o mundo de tal maneira que deu o seu Filho unigênito, para que todo aquele que nele crê não pereça, mas tenha a vida eterna".',
    biblical_reference: 'João 3:16',
    difficulty: 'facil',
    category: 'Doutrinas e Salvação',
    active: true,
  },
  {
    id: 'q-018',
    question: 'De acordo com Gálatas 5:22-23, qual destas virtudes faz parte do Fruto do Espírito?',
    option_a: 'Longanimidade (Paciência)',
    option_b: 'Eloquência',
    option_c: 'Prosperidade material',
    option_d: 'Ambição',
    correct_answer: 'A',
    explanation: 'O fruto do Espírito é: amor, alegria, paz, longanimidade, benignidade, bondade, fidelidade, mansidão e domínio próprio.',
    biblical_reference: 'Gálatas 5:22-23',
    difficulty: 'facil',
    category: 'Vida Cristã',
    active: true,
  },
  {
    id: 'q-019',
    question: 'Qual homem recebeu de Deus a promessa de que seria o pai de uma multidão de nações tão numerosa quanto as estrelas?',
    option_a: 'Noé',
    option_b: 'Abraão',
    option_c: 'Moisés',
    option_d: 'Davi',
    correct_answer: 'B',
    explanation: 'Deus tirou Abrão para fora da tenda e disse-lhe que olhasse para os céus e contasse as estrelas; assim seria a sua descendência.',
    biblical_reference: 'Gênesis 15:5; 17:4-5',
    difficulty: 'facil',
    category: 'Patriarcas',
    active: true,
  },
  {
    id: 'q-020',
    question: 'Em qual rio Jesus foi batizado por João Batista no início do Seu ministério?',
    option_a: 'Rio Nilo',
    option_b: 'Rio Eufrates',
    option_c: 'Rio Jordão',
    option_d: 'Rio Tigre',
    correct_answer: 'C',
    explanation: 'Jesus veio da Galileia ao rio Jordão para ser batizado por João Batista, momento em que o Espírito desceu como pomba.',
    biblical_reference: 'Mateus 3:13-17',
    difficulty: 'facil',
    category: 'Jesus e Evangelhos',
    active: true,
  },
  {
    id: 'q-021',
    question: 'Qual foi o homem que liderou a reconstrução dos muros caídos de Jerusalém em apenas 52 dias?',
    option_a: 'Esdras',
    option_b: 'Neemias',
    option_c: 'Zorobabel',
    option_d: 'Josias',
    correct_answer: 'B',
    explanation: 'Neemias, antigo copeiro do rei persa, mobilizou o povo e completou a reedificação das muralhas da Cidade Santa em 52 dias.',
    biblical_reference: 'Neemias 6:15',
    difficulty: 'medio',
    category: 'Antigo Testamento',
    active: true,
  },
  {
    id: 'q-022',
    question: 'Na parábola contada por Jesus, quem prestou socorro ao viajante ferido na estrada de Jericó?',
    option_a: 'O sacerdote',
    option_b: 'O levita',
    option_c: 'O bom samaritano',
    option_d: 'O centurião romano',
    correct_answer: 'C',
    explanation: 'Tanto o sacerdote quanto o levita passaram de largo, mas um samaritano, que ia de viagem, compadeceu-se e cuidou das feridas do homem.',
    biblical_reference: 'Lucas 10:30-37',
    difficulty: 'facil',
    category: 'Parábolas',
    active: true,
  },
  {
    id: 'q-023',
    question: 'Qual discípulo declarou que só acreditaria na ressurreição de Jesus se visse as marcas dos cravos nas Suas mãos?',
    option_a: 'Tiago',
    option_b: 'Tomé',
    option_c: 'Filipe',
    option_d: 'Bartolomeu',
    correct_answer: 'B',
    explanation: 'Tomé disse aos outros discípulos: "Se eu não vir nas suas mãos o sinal dos cravos... não crerei". Jesus depois apareceu e o convidou a tocar em Suas mãos.',
    biblical_reference: 'João 20:24-29',
    difficulty: 'facil',
    category: 'Novo Testamento',
    active: true,
  },
  {
    id: 'q-024',
    question: 'Qual líder sucedeu a Moisés e conduziu o povo de Israel na travessia do Jordão e conquista da Terra Prometida?',
    option_a: 'Calebe',
    option_b: 'Josué',
    option_c: 'Gideão',
    option_d: 'Balaque',
    correct_answer: 'B',
    explanation: 'Após a morte de Moisés, o Senhor falou a Josué filho de Num: "Levanta-te, passa este Jordão, tu e todo este povo, para a terra que eu dou aos filhos de Israel".',
    biblical_reference: 'Josué 1:1-2',
    difficulty: 'facil',
    category: 'Antigo Testamento',
    active: true,
  },
  {
    id: 'q-025',
    question: 'Qual apóstolo escreveu a maior quantidade de cartas registradas no Novo Testamento?',
    option_a: 'Pedro',
    option_b: 'Paulo',
    option_c: 'João',
    option_d: 'Lucas',
    correct_answer: 'B',
    explanation: 'O apóstolo Paulo é o autor de pelo menos 13 epístolas canônicas do Novo Testamento, de Romanos a Filemom.',
    biblical_reference: '2 Pedro 3:15-16',
    difficulty: 'facil',
    category: 'Novo Testamento',
    active: true,
  },
  {
    id: 'q-026',
    question: 'Quem foi vendido como escravo pelos próprios irmãos e mais tarde tornou-se governador de todo o Egito?',
    option_a: 'Benjamim',
    option_b: 'José',
    option_c: 'Judá',
    option_d: 'Rúben',
    correct_answer: 'B',
    explanation: 'José foi vendido aos ismaelitas por ciúmes de seus irmãos, mas Deus transformou o mal em bem e o elevou a governador do Egito para preservar vidas.',
    biblical_reference: 'Gênesis 37:28; 41:41; 50:20',
    difficulty: 'facil',
    category: 'Patriarcas',
    active: true,
  },
  {
    id: 'q-027',
    question: 'No dia de Pentecostes registrado em Atos 2, o que desceu sobre os discípulos reunidos no cenáculo?',
    option_a: 'Uma nuvem de fumaça',
    option_b: 'Línguas como que de fogo e o derramamento do Espírito Santo',
    option_c: 'Um terremoto que abriu o chão',
    option_d: 'Pedaços de maná',
    correct_answer: 'B',
    explanation: 'Ao cumprir-se o dia de Pentecostes, veio do céu um som como de um vento veemente, e apareceram línguas repartidas como que de fogo sobre eles.',
    biblical_reference: 'Atos 2:1-4',
    difficulty: 'facil',
    category: 'Igreja Primitiva',
    active: true,
  },
  {
    id: 'q-028',
    question: 'Qual amigo íntimo de Jesus foi ressuscitado em Betânia quatro dias após o seu sepultamento?',
    option_a: 'Jairo',
    option_b: 'Lázaro',
    option_c: 'Nicodemos',
    option_d: 'Simeão',
    correct_answer: 'B',
    explanation: 'Jesus clamou com grande voz junto à sepultura: "Lázaro, vem para fora!", e o homem que havia morrido saiu atado de mãos e pés.',
    biblical_reference: 'João 11:38-44',
    difficulty: 'facil',
    category: 'Jesus e Evangelhos',
    active: true,
  },
  {
    id: 'q-029',
    question: 'Quantos pães e peixes um jovem ofereceu a Jesus antes do milagre da primeira grande multiplicação?',
    option_a: '7 pães e 3 peixes',
    option_b: '5 pães de cevada e 2 peixinhos',
    option_c: '12 pães e 1 peixe',
    option_d: '3 pães e 2 peixes',
    correct_answer: 'B',
    explanation: 'André disse: "Está aqui um rapaz que tem cinco pães de cevada e dois peixinhos; mas que é isto para tantos?". Jesus os abençoou e alimentou cerca de cinco mil homens.',
    biblical_reference: 'João 6:9-11',
    difficulty: 'medio',
    category: 'Jesus e Evangelhos',
    active: true,
  },
  {
    id: 'q-030',
    question: 'Quem foi o homem mais idoso mencionado na genealogia bíblica, tendo vivido 969 anos?',
    option_a: 'Noé',
    option_b: 'Matusalém',
    option_c: 'Adão',
    option_d: 'Enoque',
    correct_answer: 'B',
    explanation: 'Gênesis 5:27 registra: "E foram todos os dias de Matusalém novecentos e sessenta e nove anos, e morreu".',
    biblical_reference: 'Gênesis 5:27',
    difficulty: 'medio',
    category: 'Antigo Testamento',
    active: true,
  },
  {
    id: 'q-031',
    question: 'Qual profeta foi enviado por Deus para confrontar o rei Davi pelo pecado cometido contra Urias e Bate-Seba?',
    option_a: 'Samuel',
    option_b: 'Natã',
    option_c: 'Gade',
    option_d: 'Aías',
    correct_answer: 'B',
    explanation: 'O profeta Natã contou a parábola da cordeirinha do homem pobre e declarou a Davi: "Tu és este homem!", levando o rei ao profundo arrependimento do Salmo 51.',
    biblical_reference: '2 Samuel 12:1-7; Salmos 51',
    difficulty: 'medio',
    category: 'Reis de Israel',
    active: true,
  },
  {
    id: 'q-032',
    question: 'Qual dos Evangelhos não faz parte dos chamados "Evangelhos Sinópticos"?',
    option_a: 'Mateus',
    option_b: 'Marcos',
    option_c: 'Lucas',
    option_d: 'João',
    correct_answer: 'D',
    explanation: 'Mateus, Marcos e Lucas compartilham estrutura e perspectiva sinóptica (visão em conjunto), enquanto o Evangelho de João possui enfoque teológico e narrativo próprio.',
    biblical_reference: 'João 20:30-31',
    difficulty: 'medio',
    category: 'Estudos Bíblicos',
    active: true,
  },
  {
    id: 'q-033',
    question: 'Qual rainha viajou de terras distantes para ouvir pessoalmente a sabedoria e contemplar a riqueza do rei Salomão?',
    option_a: 'Rainha de Sabá',
    option_b: 'Rainha Jezabel',
    option_c: 'Rainha Atalia',
    option_d: 'Rainha Vasti',
    correct_answer: 'A',
    explanation: 'A rainha de Sabá ouviu a fama de Salomão a respeito do nome do Senhor e veio prová-lo por enigmas, declarando que não lhe haviam contado nem a metade.',
    biblical_reference: '1 Reis 10:1-7',
    difficulty: 'facil',
    category: 'Reis de Israel',
    active: true,
  },
  {
    id: 'q-034',
    question: 'Onde o apóstolo João estava exilado quando recebeu a revelação do livro de Apocalipse?',
    option_a: 'Ilha de Creta',
    option_b: 'Ilha de Malta',
    option_c: 'Ilha de Patmos',
    option_d: 'Ilha de Chipre',
    correct_answer: 'C',
    explanation: 'João escreveu: "Eu, João... achei-me na ilha chamada Patmos, por causa da palavra de Deus e pelo testemunho de Jesus Cristo".',
    biblical_reference: 'Apocalipse 1:9',
    difficulty: 'medio',
    category: 'Novo Testamento',
    active: true,
  },
  {
    id: 'q-035',
    question: 'De acordo com 1 Coríntios 13:13, entre a fé, a esperança e o amor, qual é o maior deles?',
    option_a: 'A fé',
    option_b: 'A esperança',
    option_c: 'O amor',
    option_d: 'Todos são exatamente iguais',
    correct_answer: 'C',
    explanation: 'O apóstolo Paulo conclui o sublime cântico do amor afirmando: "Agora, pois, permanecem a fé, a esperança e o amor, estes três; mas o maior destes é o amor".',
    biblical_reference: '1 Coríntios 13:13',
    difficulty: 'facil',
    category: 'Doutrinas e Vida Cristã',
    active: true,
  },
  {
    id: 'q-036',
    question: 'Qual homem subiu ao céu sem experimentar a morte biológica, porque "andou com Deus"?',
    option_a: 'Matusalém',
    option_b: 'Enoque',
    option_c: 'Sete',
    option_d: 'Lameque',
    correct_answer: 'B',
    explanation: 'Gênesis 5:24 declara: "E andou Enoque com Deus; e não apareceu mais, porquanto Deus para si o tomou".',
    biblical_reference: 'Gênesis 5:24; Hebreus 11:5',
    difficulty: 'medio',
    category: 'Antigo Testamento',
    active: true,
  }
];
