/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as BuscaRouteImport } from './routes/busca'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as FavoritosRouteImport } from './routes/favoritos'
import { Route as OracoesRouteImport } from './routes/oracoes'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as PergunteRouteImport } from './routes/pergunte'
import { Route as PrivacidadeRouteImport } from './routes/privacidade'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as TermosRouteImport } from './routes/termos'
import { Route as VersiculoDoDiaRouteImport } from './routes/versiculo-do-dia'
import { Route as BibliaIndexRouteImport } from './routes/biblia.index'
import { Route as DevocionaisIndexRouteImport } from './routes/devocionais.index'
import { Route as DevocionaisSlugRouteImport } from './routes/devocionais.$slug'
import { Route as EstudosIndexRouteImport } from './routes/estudos.index'
import { Route as EstudosSlugRouteImport } from './routes/estudos.$slug'
import { Route as BibliaBookIndexRouteImport } from './routes/biblia.$book.index'
import { Route as EstudosCategoriaSlugRouteImport } from './routes/estudos.categoria.$slug'
import { Route as BibliaBookChapterIndexRouteImport } from './routes/biblia.$book.$chapter.index'
import { Route as BibliaBookChapterVerseRouteImport } from './routes/biblia.$book.$chapter.$verse'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const BuscaRoute = BuscaRouteImport.update({
  id: '/busca',
  path: '/busca',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritosRoute = FavoritosRouteImport.update({
  id: '/favoritos',
  path: '/favoritos',
  getParentRoute: () => rootRouteImport,
} as any)
const OracoesRoute = OracoesRouteImport.update({
  id: '/oracoes',
  path: '/oracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const PergunteRoute = PergunteRouteImport.update({
  id: '/pergunte',
  path: '/pergunte',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadeRoute = PrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const TermosRoute = TermosRouteImport.update({
  id: '/termos',
  path: '/termos',
  getParentRoute: () => rootRouteImport,
} as any)
const VersiculoDoDiaRoute = VersiculoDoDiaRouteImport.update({
  id: '/versiculo-do-dia',
  path: '/versiculo-do-dia',
  getParentRoute: () => rootRouteImport,
} as any)
const BibliaIndexRoute = BibliaIndexRouteImport.update({
  id: '/biblia/',
  path: '/biblia/',
  getParentRoute: () => rootRouteImport,
} as any)
const DevocionaisIndexRoute = DevocionaisIndexRouteImport.update({
  id: '/devocionais/',
  path: '/devocionais/',
  getParentRoute: () => rootRouteImport,
} as any)
const DevocionaisSlugRoute = DevocionaisSlugRouteImport.update({
  id: '/devocionais/$slug',
  path: '/devocionais/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const EstudosIndexRoute = EstudosIndexRouteImport.update({
  id: '/estudos/',
  path: '/estudos/',
  getParentRoute: () => rootRouteImport,
} as any)
const EstudosSlugRoute = EstudosSlugRouteImport.update({
  id: '/estudos/$slug',
  path: '/estudos/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BibliaBookIndexRoute = BibliaBookIndexRouteImport.update({
  id: '/biblia/$book/',
  path: '/biblia/$book/',
  getParentRoute: () => rootRouteImport,
} as any)
const EstudosCategoriaSlugRoute = EstudosCategoriaSlugRouteImport.update({
  id: '/estudos/categoria/$slug',
  path: '/estudos/categoria/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BibliaBookChapterIndexRoute = BibliaBookChapterIndexRouteImport.update({
  id: '/biblia/$book/$chapter/',
  path: '/biblia/$book/$chapter/',
  getParentRoute: () => rootRouteImport,
} as any)
const BibliaBookChapterVerseRoute = BibliaBookChapterVerseRouteImport.update({
  id: '/biblia/$book/$chapter/$verse',
  path: '/biblia/$book/$chapter/$verse',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/busca': typeof BuscaRoute
  '/contato': typeof ContatoRoute
  '/cookies': typeof CookiesRoute
  '/favoritos': typeof FavoritosRoute
  '/oracoes': typeof OracoesRoute
  '/perfil': typeof PerfilRoute
  '/pergunte': typeof PergunteRoute
  '/privacidade': typeof PrivacidadeRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/termos': typeof TermosRoute
  '/versiculo-do-dia': typeof VersiculoDoDiaRoute
  '/devocionais/$slug': typeof DevocionaisSlugRoute
  '/estudos/$slug': typeof EstudosSlugRoute
  '/biblia/': typeof BibliaIndexRoute
  '/devocionais/': typeof DevocionaisIndexRoute
  '/estudos/': typeof EstudosIndexRoute
  '/estudos/categoria/$slug': typeof EstudosCategoriaSlugRoute
  '/biblia/$book/': typeof BibliaBookIndexRoute
  '/biblia/$book/$chapter/$verse': typeof BibliaBookChapterVerseRoute
  '/biblia/$book/$chapter/': typeof BibliaBookChapterIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/busca': typeof BuscaRoute
  '/contato': typeof ContatoRoute
  '/cookies': typeof CookiesRoute
  '/favoritos': typeof FavoritosRoute
  '/oracoes': typeof OracoesRoute
  '/perfil': typeof PerfilRoute
  '/pergunte': typeof PergunteRoute
  '/privacidade': typeof PrivacidadeRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/termos': typeof TermosRoute
  '/versiculo-do-dia': typeof VersiculoDoDiaRoute
  '/devocionais/$slug': typeof DevocionaisSlugRoute
  '/estudos/$slug': typeof EstudosSlugRoute
  '/biblia': typeof BibliaIndexRoute
  '/devocionais': typeof DevocionaisIndexRoute
  '/estudos': typeof EstudosIndexRoute
  '/estudos/categoria/$slug': typeof EstudosCategoriaSlugRoute
  '/biblia/$book': typeof BibliaBookIndexRoute
  '/biblia/$book/$chapter/$verse': typeof BibliaBookChapterVerseRoute
  '/biblia/$book/$chapter': typeof BibliaBookChapterIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/busca': typeof BuscaRoute
  '/contato': typeof ContatoRoute
  '/cookies': typeof CookiesRoute
  '/favoritos': typeof FavoritosRoute
  '/oracoes': typeof OracoesRoute
  '/perfil': typeof PerfilRoute
  '/pergunte': typeof PergunteRoute
  '/privacidade': typeof PrivacidadeRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/termos': typeof TermosRoute
  '/versiculo-do-dia': typeof VersiculoDoDiaRoute
  '/devocionais/$slug': typeof DevocionaisSlugRoute
  '/estudos/$slug': typeof EstudosSlugRoute
  '/biblia/': typeof BibliaIndexRoute
  '/devocionais/': typeof DevocionaisIndexRoute
  '/estudos/': typeof EstudosIndexRoute
  '/estudos/categoria/$slug': typeof EstudosCategoriaSlugRoute
  '/biblia/$book/': typeof BibliaBookIndexRoute
  '/biblia/$book/$chapter/$verse': typeof BibliaBookChapterVerseRoute
  '/biblia/$book/$chapter/': typeof BibliaBookChapterIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/busca'
    | '/contato'
    | '/cookies'
    | '/favoritos'
    | '/oracoes'
    | '/perfil'
    | '/pergunte'
    | '/privacidade'
    | '/sitemap.xml'
    | '/termos'
    | '/versiculo-do-dia'
    | '/devocionais/$slug'
    | '/estudos/$slug'
    | '/biblia/'
    | '/devocionais/'
    | '/estudos/'
    | '/estudos/categoria/$slug'
    | '/biblia/$book/'
    | '/biblia/$book/$chapter/$verse'
    | '/biblia/$book/$chapter/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/busca'
    | '/contato'
    | '/cookies'
    | '/favoritos'
    | '/oracoes'
    | '/perfil'
    | '/pergunte'
    | '/privacidade'
    | '/sitemap.xml'
    | '/termos'
    | '/versiculo-do-dia'
    | '/devocionais/$slug'
    | '/estudos/$slug'
    | '/biblia'
    | '/devocionais'
    | '/estudos'
    | '/estudos/categoria/$slug'
    | '/biblia/$book'
    | '/biblia/$book/$chapter/$verse'
    | '/biblia/$book/$chapter'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/busca'
    | '/contato'
    | '/cookies'
    | '/favoritos'
    | '/oracoes'
    | '/perfil'
    | '/pergunte'
    | '/privacidade'
    | '/sitemap.xml'
    | '/termos'
    | '/versiculo-do-dia'
    | '/devocionais/$slug'
    | '/estudos/$slug'
    | '/biblia/'
    | '/devocionais/'
    | '/estudos/'
    | '/estudos/categoria/$slug'
    | '/biblia/$book/'
    | '/biblia/$book/$chapter/$verse'
    | '/biblia/$book/$chapter/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  BuscaRoute: typeof BuscaRoute
  ContatoRoute: typeof ContatoRoute
  CookiesRoute: typeof CookiesRoute
  FavoritosRoute: typeof FavoritosRoute
  OracoesRoute: typeof OracoesRoute
  PerfilRoute: typeof PerfilRoute
  PergunteRoute: typeof PergunteRoute
  PrivacidadeRoute: typeof PrivacidadeRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermosRoute: typeof TermosRoute
  VersiculoDoDiaRoute: typeof VersiculoDoDiaRoute
  DevocionaisSlugRoute: typeof DevocionaisSlugRoute
  EstudosSlugRoute: typeof EstudosSlugRoute
  BibliaIndexRoute: typeof BibliaIndexRoute
  DevocionaisIndexRoute: typeof DevocionaisIndexRoute
  EstudosIndexRoute: typeof EstudosIndexRoute
  EstudosCategoriaSlugRoute: typeof EstudosCategoriaSlugRoute
  BibliaBookIndexRoute: typeof BibliaBookIndexRoute
  BibliaBookChapterVerseRoute: typeof BibliaBookChapterVerseRoute
  BibliaBookChapterIndexRoute: typeof BibliaBookChapterIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/busca': {
      id: '/busca'
      path: '/busca'
      fullPath: '/busca'
      preLoaderRoute: typeof BuscaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favoritos': {
      id: '/favoritos'
      path: '/favoritos'
      fullPath: '/favoritos'
      preLoaderRoute: typeof FavoritosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oracoes': {
      id: '/oracoes'
      path: '/oracoes'
      fullPath: '/oracoes'
      preLoaderRoute: typeof OracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pergunte': {
      id: '/pergunte'
      path: '/pergunte'
      fullPath: '/pergunte'
      preLoaderRoute: typeof PergunteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidade': {
      id: '/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/termos': {
      id: '/termos'
      path: '/termos'
      fullPath: '/termos'
      preLoaderRoute: typeof TermosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/versiculo-do-dia': {
      id: '/versiculo-do-dia'
      path: '/versiculo-do-dia'
      fullPath: '/versiculo-do-dia'
      preLoaderRoute: typeof VersiculoDoDiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/biblia/': {
      id: '/biblia/'
      path: '/biblia'
      fullPath: '/biblia/'
      preLoaderRoute: typeof BibliaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/devocionais/': {
      id: '/devocionais/'
      path: '/devocionais'
      fullPath: '/devocionais/'
      preLoaderRoute: typeof DevocionaisIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/devocionais/$slug': {
      id: '/devocionais/$slug'
      path: '/devocionais/$slug'
      fullPath: '/devocionais/$slug'
      preLoaderRoute: typeof DevocionaisSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estudos/': {
      id: '/estudos/'
      path: '/estudos'
      fullPath: '/estudos/'
      preLoaderRoute: typeof EstudosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estudos/$slug': {
      id: '/estudos/$slug'
      path: '/estudos/$slug'
      fullPath: '/estudos/$slug'
      preLoaderRoute: typeof EstudosSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/biblia/$book/': {
      id: '/biblia/$book/'
      path: '/biblia/$book'
      fullPath: '/biblia/$book/'
      preLoaderRoute: typeof BibliaBookIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estudos/categoria/$slug': {
      id: '/estudos/categoria/$slug'
      path: '/estudos/categoria/$slug'
      fullPath: '/estudos/categoria/$slug'
      preLoaderRoute: typeof EstudosCategoriaSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/biblia/$book/$chapter/': {
      id: '/biblia/$book/$chapter/'
      path: '/biblia/$book/$chapter'
      fullPath: '/biblia/$book/$chapter/'
      preLoaderRoute: typeof BibliaBookChapterIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/biblia/$book/$chapter/$verse': {
      id: '/biblia/$book/$chapter/$verse'
      path: '/biblia/$book/$chapter/$verse'
      fullPath: '/biblia/$book/$chapter/$verse'
      preLoaderRoute: typeof BibliaBookChapterVerseRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  BuscaRoute: BuscaRoute,
  ContatoRoute: ContatoRoute,
  CookiesRoute: CookiesRoute,
  FavoritosRoute: FavoritosRoute,
  OracoesRoute: OracoesRoute,
  PerfilRoute: PerfilRoute,
  PergunteRoute: PergunteRoute,
  PrivacidadeRoute: PrivacidadeRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermosRoute: TermosRoute,
  VersiculoDoDiaRoute: VersiculoDoDiaRoute,
  DevocionaisSlugRoute: DevocionaisSlugRoute,
  EstudosSlugRoute: EstudosSlugRoute,
  BibliaIndexRoute: BibliaIndexRoute,
  DevocionaisIndexRoute: DevocionaisIndexRoute,
  EstudosIndexRoute: EstudosIndexRoute,
  EstudosCategoriaSlugRoute: EstudosCategoriaSlugRoute,
  BibliaBookIndexRoute: BibliaBookIndexRoute,
  BibliaBookChapterVerseRoute: BibliaBookChapterVerseRoute,
  BibliaBookChapterIndexRoute: BibliaBookChapterIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
